use_frameworks!

platform :ios, '8.0'

target 'HLKit_Example' do
  pod 'HLKit', :path => '../'
  pod 'AFNetworking','3.1.0'
  #pod 'SDWebImage','5.0.6'

  target 'HLKit_Tests' do
    inherit! :search_paths

  end
  
end
