source 'https://github.com/HLCrawler/HLSpecA.git'

use_frameworks!

platform :ios, '8.0'

target 'HLKit_Example' do
  pod 'HLKit', :path => '../'
  pod 'AFNetworking','3.1.0'
  pod 'HLMediator'

  target 'HLKit_Tests' do
    inherit! :search_paths

  end
  
end
